# fly.toml app configuration file generated for bold-resonance-4564 on 2023-10-25T17:08:18-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bold-resonance-4564"
primary_region = "scl"

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
